### ISSUE TITLE
multi-line patterns should not include indention in value

### ISSUE THREAD

**Issue by Pike** [projectfluent/fluent#150]
This seems to be a regression in the 0.6 work.

For a

```
message = something
  indented
```

the leading whitespace is now part of the value, which it wasn't in 0.5 in practice.

I think that in particular in the scope of 0.6, we shouldn't make such changes.

**Comment by stasm** [comment]
Do you mean that we shouldn't do it in 0.6, or that we shouldn't do it all?

IIRC, this was a deliberate decision. We even have the following code in the parser to enforce this behavior when the first token on the next line is a placeable:

https://github.com/projectfluent/fluent/blob/d2a5363f413d9b963f9b2299329760156e6a7ba9/syntax/grammar.mjs#L141-L149

I think this is fine in the 0.6 scope. To reiterate, 0.6 is about cleanups which don't change the syntax. We're changing the semantics and AST _a lot_ in 0.6 :)

**Comment by Pike** [comment]
I think we shouldn't do this, and we shouldn't do this in 0.6.

On master, you can't create the following string value:

```
First line.
Second line.
```

We could do that in 0.5, in that way I consider this to be a regression. Do we have other cases in 0.6 where the same ftl file results in different runtime behavior?

This decision also forces our hands in #122, I think, as that'd be the only way to add actual multiline text back.

The up-side of this is that we preserve white-space in multi-line text, which is probably what made me eager to have this. But looking back, I think that white-space preservation is more in scope of #121.

**Comment by stasm** [comment]
(I'm still thinking about this; for now I'd like to respond to your comments.)

> We could do that in 0.5, in that way I consider this to be a regression. Do we have other cases in 0.6 where the same ftl file results in different runtime behavior?

No, there aren't any other cases. However, I'd argue that this doesn't change the current runtime behavior either, because a) we currently heavily rely on the environment's whitespace normalization and b) we'll define the spec for this in #122 in 0.7, so it's OK to leave it up to the env for now.

> This decision also forces our hands in #122, I think, as that'd be the only way to add actual multiline text back.

What's "that" (in _that would be) in this sentence?

**Comment by Pike** [comment]
> What's "that" (in that would be) in this sentence?

"That" would be that we should provide a way to serialize a two line string w/out leading whitespace.

**Comment by stasm** [comment]
Thanks. And sorry, I still don't understand how it ties our hands in #122.  None of the current implementations would be affected by the leading whitespace being present (or missing) in the AST. Why wouldn't we leave the current master's behavior in 0.6, and properly design this in 0.7?

**Comment by stasm** [comment]
I implemented the behavior from 0.5 in #151. I think we can go either way:

 1. Leave this as-is on master because it has zero impact on the current runtimes.
 2. Take the fix and discuss this further in #122.

Both seem sane to me. If the PR in #151 gets an r+, I'm OK with the option no. 2. We'll have a chance to revisit this in #122 at which point we might reintroduce those indents.

**Comment by stasm** [comment]
@zbraniecki Do you have an opinion about this? I know you've already implemented the behavior from the current master (i.e., preserving the indents) in `fluent-syntax`. Thanks for that PR. Do you have any feedback from the imlementer's POV?

**Comment by zbraniecki** [comment]
> Do you have any feedback from the imlementer's POV?

Not really. Both are relatively easy codepaths, nothing really stands out. Either way is fine, so your call.

**Comment by stasm** [comment]
Thanks, @zbraniecki. And thanks, @Pike, for raising this issue. Let's revert back to the 0.5 behavior in 0.6 for maximum compatibility. We'll discuss this proper in #122.
