### ISSUE TITLE
Can fluent be used in a C/C++ project?

### ISSUE THREAD

**Issue by lyndalopez544** [projectfluent/fluent#275]

**Comment by Pike** [comment]
The way to do this will be by exposing https://github.com/projectfluent/fluent-rs. I read last night on irc that @zbraniecki might need to dig into that.

To be convenient to use from C++, it should probably get a healthy dose of template magic for things like variable references.

**Comment by zbraniecki** [comment]
I think we can close this. `fluent-rs` is available and can be used from C/C++ via `bindgen`.

**Comment by tustin2121** [comment]
> I think we can close this. `fluent-rs` is available and can be used from C/C++ via `bindgen`.

First off, `bindgen` doesn't make C++ headers from Rust, it makes Rust headers from C++. It looks like there's another project [`cbindgen`](https://lib.rs/crates/cbindgen) that does the latter.

Secondly, this is *not a solution.* [C++ developers do not want to have to deal with another language if they want to use Fluent.](https://gitlab.com/OpenMW/openmw/-/merge_requests/620) I really want to use Fluent as my i18n solution. I wanted to use it three years ago when I first found this issue at the top of the google search results, and I want to use it now as I'm starting a new project. And it's baffling to me that *this* remains the top result for "Project Fluent C++": basically an admission that you're not gonna support C++.

If you guys want Fluent to take off, as I do because it looks really cool, you need to *at least* provide a *tutorial* on how to use it in C/C++. [C/C++ combined are still 4 times as popular as Rust](https://survey.stackoverflow.co/2022#most-popular-technologies-language). 

For incoming Googlers, I found [this abandoned project on GitLab](https://gitlab.com/bmwinger/fluent-cpp) which the maintainer [said in a pull request](https://gitlab.com/OpenMW/openmw/-/merge_requests/1245) isn't fully implemented. That seems to be all we have in terms of third-party implementations.
