### ISSUE TITLE
Allow dots in message identifiers

### ISSUE THREAD

**Issue by slavafomin** [projectfluent/fluent#341]
Hello!

First of all, thank you for this great library. I've studied several i18n standards and message formats and have found that Fluent has all the required features and at the same time provides a very clear and user-friendly message format. I'm planning to use it for all of our future projects.

I'm a maintainer of several Fluent integration libraries:
- [@moebius/fluent](https://github.com/the-moebius/fluent)
- [@moebius/grammy-fluent](https://github.com/the-moebius/grammy-fluent)

However, when migrating from other message format I've stumbled upon a very nasty drawback: Fluent won't allow dots (".") in message identifiers.

I have the following message structure in my application: `feature.section.property`, e.g.: `settings.menu-buttons.change-language`, but Fluent is not allowing me to use this format, because dots are for some reason forbidden.

Using dots are a very common way to represent nested elements in many standards. It would really help with the Fluent adoption if it would allow using dots in identifiers. Is there any particular reason why this is not allowed now?

Thanks!

**Comment by spookylukey** [comment]
I presume they are not allowed because of the confusion this would introduce with attributes - https://projectfluent.org/fluent/guide/attributes.html
Note also that `.` is often used as a fully qualified name for an attribute e.g. `-my-term.my-attribute`, and this is used for example in selectors https://github.com/projectfluent/python-fluent/blob/c58681f1e90c14dd36c2ff35d7d487235b685177/fluent.runtime/tests/format/test_select_expression.py#L184

**Comment by slavafomin** [comment]
@spookylukey thank you for pointing that out, I actually have thought of that, but I don't think that one conflicts with another: e.g. when you have the following ID: `foo.bar.baz`, the resolver could first check if the ID with the full name `foo.bar.baz` exists and if it's not then check for ID `foo.bar` and an attribute `baz`.

**Comment by alerque** [comment]
Having to first check one set of keys and if not found check another set would be a significant downside as far as assorted language implementations go. It would mean you couldn't take shortcuts like using language features to check the existence of an array key, you'd have to write a custom key lookup function and use it all the time. While solvable, I'm not sure the benefit here (to programmers) outweighs the new pain point (also to programmers).

**Comment by eemeli** [comment]
@spookylukey is correct in his presumption here; dots are used as separators between message and attribute identifiers and therefore not allowed in the identifiers themselves.

@slavafomin If an `Identifier` was allowed to also contain the `.` character, this would create a number of ambiguities. To continue with your example of a message reference `foo.bar.baz`, what if there's also a message `foo` with an attribute `bar.baz`? It would be unclear which is being referred to.

If adapting a `feature.section.property` style of message names to Fluent, my recommendation would be to use `_` as a separator instead, resulting in e.g. `settings_menu-buttons_change-language`.

**Comment by oovm** [comment]
how about use `::` or simply `:` as a separator?

**Comment by alerque** [comment]
> how about use `::` or simply `:` as a separator?

It's not a matter of what separator to use, it's a matter of whether to use a separator at all. Using one (any one) [has significant downsides](https://github.com/projectfluent/fluent/issues/341#issuecomment-1000912634)

If you are just suggestion an informal scheme for the sake of organizing it the programmer's head, you can use any combinations of characters you like as long as they are valid identifiers. No change is required in Fluent for that to be possible...

...and as suggested above no change to Fluent is being considered to allow dots in identifiers. As such I think it is time this issue got closed since it is as resolved as anybody plans on it being so.

**Comment by eemeli** [comment]
I agree with @alerque, there isn't really anything more here that's actionable.
