### ISSUE TITLE
Make  `[]` legal in selector

### ISSUE THREAD

**Issue by AndyJado** [projectfluent/fluent#353]
I don't see progress in [empty/null/undefined in selector](https://github.com/projectfluent/fluent/issues/310) 

but is there a way I can do the following code less painful?

```
if-I-have-empty-string-in-selector = 
    {$hello ->
        [] {""}
        *[other] {$hello} there
    }
```

**Comment by alerque** [comment]
I don't think opening a new issue to say "no progress on old issue" is very helpful.

No answer the question, the current "correct" way to do this is with two messages and use your program logic to pick the correct message, one for when you have variables to send and a different message for when you have nothing to send.

**Comment by AndyJado** [comment]
well my problem is I believe that issue still has no progress for two years somehow is a issue ;)

if you have string based selector, however some specific string is implicitly illegal, may I ask why? a empty string not considered a string?

**Comment by alerque** [comment]
> a empty string not considered a string?

Because in most programming languages an array key cannot be empty. There may be a use for it in this case, but that's exactly what the other issue proposes and there is lots of discussion about the ups and downs it will entail in various languages. If you have something to add to that discussion weigh in there, there is not point in rehashing it in a new thread and scattering the info. Scattered discussions just makes it harder to act on an issue.

**Comment by AndyJado** [comment]
> Because in most programming languages an array key cannot be empty.

okay I see the intention now, thank you for sharing.
