### ISSUE TITLE
Support for array data in externals

### ISSUE THREAD

**Issue by aiwenar** [projectfluent/fluent#46]
In L20n v4 we were able to pass arrays in externals, have them formatted, and transform them (to an extent) using `TAKE` and `DROP` functions. After inception of fluent and L20n v5 attempts to use arrays now result in a `Unsupported external type: array, object` TypeError and I was unable to find any mentions of arrays in fluent specification or fluent/l20n source code, nor was there any mention of their removal in L20n's changelog.

Therefore I'd like to ask: was array support removed on purpose? If so what's recommended for projects which were using arrays, if not what's the plan on bringing them back?

**Comment by aiwenar** [comment]
My college has just pointed me to a [commit](https://github.com/projectfluent/fluent/commit/529600ff0e98a84f7e6f905bd6f17df8731b3455) I missed which removes lists from Fluent specs. While this answers the first part of my question I still think that should be noted in https://github.com/l20n/l20n.js/blob/master/CHANGELOG.md.

**Comment by stasm** [comment]
Hi @aiwenar, thanks for filing the issue. As you pointed out we removed the List type because of the complexity it added to the design and the implementation.  For instance, each item of the list would need to be formatted when interpolated into a translation, and the list itself would need to be formatted according to the current language as well. See https://github.com/zbraniecki/proposal-intl-list-format for more information on the proposed standard for doing this.

I agree we should have mentioned this in the CHANGELOG.

As an additional note, it is still possible to pass custom Functions to the `MessageContext` constructor. See http://projectfluent.io/fluent.js/fluent/MessageContext.html.  L20n.js creates `MessageContext` instances automatically, but if you're willing to write your own glue code you can use [fluent-dom](https://github.com/projectfluent/fluent.js/tree/master/fluent-dom) and create your own:

```javascript
new MessageContext(locales, {
    functions: {
        LIST: arg => /* … format `arg` here … */,
        LEN: arg => arg.length
    }
});
```

**Comment by stasm** [comment]
I'm going to close this issue as we don't currently plan to add the support for Array types.
