### ISSUE TITLE
Fix diagram comment sigil

### ISSUE THREAD

**Issue by ariasuni** [projectfluent/fluent#48]
According to #28, at some point you used `#` as the comment sigil but now it’s `//`.

Please fix your [diagram](http://projectfluent.io/fluent/spec/diagram.xhtml) which still use `#`.

**Comment by stasm** [comment]
Thanks for filing this issue and for your patience. I updated the diagram to reflect version 0.3.0 of the Syntax: e87965bdd8e2a3ff9cef0ff0d3ebb20352bc9a2a. I also created a wiki page describing the release process so that I don't forget about the diagram in the future: https://github.com/projectfluent/fluent/wiki/Publishing-Fluent-Syntax-Spec
