### ISSUE TITLE
Definition recursion: inline-expression vs argument

### ISSUE THREAD

**Issue by ctjhoa** [projectfluent/fluent#55]
Hi,

I'm not familiar with language grammar but I find something weird with the `inline-expression` & `argument` definitions.

According to the [ebnf](https://github.com/projectfluent/fluent/blob/master/spec/fluent.ebnf),
- `inline-expression` is defined by `call-expression`
- `call-expression` is defined by `argument`
- `argument` is defined by `inline-expression`

This is weird because it introduce recursion in parser implementation. Is it intended? Does `call-expression` should not be defined by `named-argument` instead?

To give context, I work on a Rust fluent parser.
https://github.com/ctjhoa/fluent-rs

Thanks

**Comment by zbraniecki** [comment]
Hi @ctjhoa ! I don't have a direct answer to your question, but you may find this interesting - https://github.com/zbraniecki/fluent-rs

I wrote the parser (albeit didn't update it to latest grammar yet!) and some basic foundation for the `MessageContext`.

It's very early code and I believe the code could use some love from someone with better Rust skills than mine.
Maybe we could join forces? :)

**Comment by ctjhoa** [comment]
@zbraniecki 
Indeed very interesting :P
I already knew [seanmonstar/l20n.rs](https://github.com/seanmonstar/l20n.rs) project to be a useful resource but I didn't know that some other guy working on a fluent implementation.

My goal is to write a fully tested parser with [nom](https://github.com/Geal/nom).
I will take a closer look at your project.

Thanks

**Comment by ctjhoa** [comment]
@stasm still no feedback on this?

**Comment by stasm** [comment]
Thanks for your question and your patience, @ctjhoa. Recursion like this is common in grammars. In this case it allows the `call-expression` to take inline expressions as positional (not named) arguments:

    key = { FUNC("foo") }
    key = { FUNC(1) }
    key = { FUNC($arg) }
    key = { FUNC(iden) }

You'll note that the same recursion is present in the `placeable` → `inline-expression` → `placeable` chain.

As far as I understand it, some top-down parsers have troubles parsing recursive grammars if they use _left recursion_. Parsing `1 + 2 + 3` with the following grammar would be bad:

    sum ::= (sum '+' )? [0-9]

Left recursion makes the parser go infinitely in a loop because the first thing it's trying to parse for a given production is the same production. In the example above the parser starts with a `sum` and encounters `1`, which matches the `sum` production, so the parser decides to parse another `sum`; the current production is still `1`, which matches the `sum` etc.. But if we switch the productions around, the parser can handle it no problem:

    sum ::= [0-9] ('+' sum)?

Let me know if you have more questions and feel free to close this issue if you agree.

**Comment by ctjhoa** [comment]
Thanks for the explanation, it's my first parser so I'm newbie.
I'm gonna dive into this.
