### ISSUE TITLE
Forbid "?" in the identifier

### ISSUE THREAD

**Issue by zbraniecki** [projectfluent/fluent#65]
As per Stas' request in https://github.com/projectfluent/fluent.js/issues/84#issuecomment-343152460

> This is one of those things that I don't think developers will actively ask us to introduce but they might
> appreciate it if it's there. If you feel strongly about forbidding the question mark (at least right now) and my
> above arguments haven't convinced you otherwise, please file a new issue in the Fluent Syntax repo.

I am not convinced and I would see a value in not adding this sygil at this point.

My reasoning boils down to two items:

1) I think of l10n-id as an identifier, not a quasi representation of the english sentence (much like Axel's point in the linked discussion). Dashes stretch it, question mark breaks it.
2) Adding sygils is irreverisble and in result should be avoided when possible. There's no request for it, there's no parity with other systems issue, there's no prior experience of people using such a thing and overall, trying to convey the role of the phrase in via the "?" in the ID seems to me like a misplaced goal.

I'd love to use as few sygils in the ID as possible and the `[a-Z_-0-9]` is imho the far end of what we should start with.

**Comment by stasm** [comment]
For posterity, I'm pasting my argument _for_ allowing the question mark. The previous discussion about this was in #49.

This is not about using English punctuation in identifiers but rather about communicating the role of the message better. Software inherently ends up asking questions via the UI. Allowing the question mark in identifiers makes it easier to communicate the intent without thinking too much about naming conflicts.

Instead of using longer ids like `delete-all-prompt` or `delete-all-confirm`, it allows for this:

```
delete-all? = Really delete all files?
delete-all = Yes, delete all files.
```

For this reason, question mark is in fact a valid character in identifiers in many languages. I know of at least Clojure, Elixir, Ruby and Scala that allow it.

We've also seen developers use the question mark in Gaia. I found examples similar to the following one in the localizations of the [Camera](https://hg.mozilla.org/gaia-l10n/en-US/file/tip/apps/gallery/gallery.properties#l9), Dialer, Gallery, and Videos apps:

```
delete-photo? = Delete photo?
delete-video? = Delete video?
```

**Comment by stasm** [comment]
Since we can always allow `?` in identifiers if no other use for it is found in the future, let's forbid it for now. I'd like to revisit this decision post-1.0 after we've gathered feedback from developers.
