### ISSUE TITLE
How to return an empty message

### ISSUE THREAD

**Issue by fernandogmar** [projectfluent/fluent#77]
Hello!

I am just trying to do this:

```
test = {  $num ->
    *[0]         
     [other]         No empty text
}
```
but it gets an error:
```
TypeError
Cannot read property 'undefined' of undefined
```

How can an empty string be returned?

**Comment by stasm** [comment]
You ran into two paper-cuts here, both of which we're currently working on :) Hopefully the next release of the syntax spec ([0.5](https://github.com/projectfluent/fluent/milestone/4)) will solve both of them!

First, it's currently required to indent _all_ of the message's body, including the closing brace `}` on the last line of your example. This will be fixed by #42.

#63 has a recommendation on how to explicitly define empty-string values: `{""}`. It a placeable with an empty string inside. Consider the following snippet:

```properties
test =
    { $num ->
         [0] {""}
        *[other] No empty text
    }
```

You can see it live in the [Playground](http://projectfluent.org/play/?gist=fcca8a8220df936ad67b268d516f724d) (use the Config tab to change the value of `$num`).

**Comment by fernandogmar** [comment]
Thanks `{""}` worked like a charm ;)

**Comment by stasm** [comment]
Glad to hear! I'm going to close this issue now. Feel free to open a new one if you have any other questions.
