### ISSUE TITLE
Is there any project that implements this in C#?

### ISSUE THREAD

**Issue by ArmsOfSorrow** [projectfluent/fluent#93]
I have looked on google but found nothing. It would be really nice to have this in C#/.NET Standard projects as it would allow usage in Mono/Unity3D and many other CLR implementations.

**Comment by ExE-Boss** [comment]
It would also be useful to have this implemented in Java as well.

**Comment by stasm** [comment]
I'd love to see a C# implementation of Fluent! In particular I think it would be great to be able to use it from within Unity3D. Fluent is a great match for gamedev and in fact some of the features and discussions have been inspired and motivated by it (e.g. #80).

The primary driver for Fluent's development has been Firefox and we've only focused on the implementations which are required in order to migrate Firefox to Fluent. I expect that this will continue to be the case at least for the next 3-6 months. I can't commit to creating the C# implementation myself but I'd love to see it as a community contribution.

We're getting very close to Fluent 1.0. The [roadmap](https://github.com/projectfluent/fluent/wiki/Roadmap) puts it at the end of June. Once it's published it will make a great base for more implementations.

I'm aware of at least one effort by @GlenDC to create a C# implementation of L20n. It stared as https://github.com/GlenDC/L10n.cs which now appears to have moved to https://github.com/polylingo/l20n.cs. See the [Unity thread](https://forum.unity.com/threads/released-l20n-a-free-and-opensource-plugin-to-localize-your-game.420380/) for more information. Glen also wrote an insightful article about [localization in gamdev](https://medium.com/@ORPH4NUS/improving-localization-in-video-games-one-step-at-a-time-f83be4882085) which is a great read.

L20n was Fluent's predecessor and is now deprecated, but its ideas live on in Fluent. The syntax has changed, however, so the implementation would have to be updated (preferably after Fluent 1.0 is published).

**Comment by ExE-Boss** [comment]
> > It would also be useful to have this implemented in Java as well.
>
> We talked a bit about this recently, and our initial take was to consider Kotlin rather than Java. Do you have an opinion on Kotlin as a target?

Well, Kotlin runs on the JVM, so it should be rather compatible with Java, although it might possibly need a few helper classes, similar to when dealing with Java ⇔ Scala calls. Granted, the need for those has significantly lessened since Java 8 and Scala 2.12.

**Comment by stasm** [comment]
I just learned about https://github.com/blushingpenguin/Fluent.Net by @blushingpenguin. It looks promising!

**Comment by stasm** [comment]
I'm going to close this issue since the answer is now: yes :) I opened a few issues in `Fluent.Net` but I haven't yet had time to take a deeper look at the code. @blushingpenguin, feel free to ping me if you have any questions or if you run into any troubles.

**Comment by Ygg01** [comment]
Hi, I did publish a lib for Fluent called Linguini, https://github.com/Ygg01/Linguini

It's not perfect but I think it is a faithful port of `fluent.rs`
