### ISSUE TITLE
Define and document linting rules for Fluent

### ISSUE THREAD

**Issue by Pike** [projectfluent/fluent#99]
We talk a lot about linters these days, but we don't have a place where we document Fluent's intent for that.

I think we should also find a name for that doc that isn't *Linting*, as I consider that to be an implementation detail. I talked about *Well-formed* vs *Valid* in #97, maybe that's a good start?

Where should we put this? projectfluent.org or on the wiki here?

CC @stasm, @flodolo, @hkasemir, @zbraniecki

**Comment by stasm** [comment]
We definitely needs this. Currently way too often do we use _linting_ as the silver bullet answer for all syntax questions :)

Let's use the wiki first so that we can edit freely. I like the distinction between _well-formed_ and _valid_. In the XML meaning of the words, would _validation_ require some kind of additional metadata about the available builtins?

**Comment by zbraniecki** [comment]
I like rust's separation between `cargo check`, `cargo fmt` and `cargo clippy` - check verifies that the syntax is correct, fmt normalizes the formatting, clippy advises on the use of the language.

I imagine our `check` warning on missing variables, plural categories and report erros, fmt normalizing whitespace, while clippy advising on use of redundant parts of a message, or potential refactors.

**Comment by zbraniecki** [comment]
is there actually a use case which wants `did it parse?` but not `does it make sense?`? In rust case, `undefined.prop` would raise a warning in `cargo check`

**Comment by stasm** [comment]
> is there actually a use case which wants did it parse? but not does it make sense??

Yes, it's editing FTL. Making it easier to write well-formed FTL means less frustration because the thing you just wrote didn't parse at all. In fact, by making it parse, you can easily syntax-highlight it _and_ run static analysis to give hints and warnings about the semantics.

Rust is infamous for not being very friendly at first and many people describe the experience as _wrestling_ with the compiler. I think it's OK for Rust to require some effort to learn. I don't think, however, that localizers have the same budget of patience as aspiring Rust developers. I wouldn't want anyone to _wrestle_ with Fluent :)

> In rust case, undefined.prop would raise a warning in cargo check

Right, but there are two separate steps involved. First, the syntax is parsed and it produces a valid AST. Then, `rustc` imbues this AST with semantics—and it warns about something which makes little sense.

**Comment by stasm** [comment]
I created a stub of validation rules at https://github.com/projectfluent/fluent/wiki/Syntax-Semantics. I'm happy to extend it when I'm back from vacation next week.

In https://github.com/stasm/fluent-kombi/commit/89c8bed7fdec03fcafbdeaf8c0d315ba9ca2f976 I implemented an example of validation run when transforming the concrete parse tree to the abstract one.

**Comment by stasm** [comment]
#97 and #102 introduced a validation step in `syntax/abstract.mjs` which transforms a well-formed AST into a valid AST. I translated the rules written in code into a set of CSS-like (but not quite) rules on the [Syntax Semantics](https://github.com/projectfluent/fluent/wiki/Syntax-Semantics) wiki page.

Before I close this issue, I plan to open a PR which moves the Syntax Semantics wiki page to the `spec/` directory in the repo. It _is_ part of the spec, after all.

**Comment by stasm** [comment]
I removed the _Syntax Semantics_ wiki page now that `spec/valid.md` has landed.
